# Generated by Django 4.0.3 on 2022-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=40)),
                ('age', models.IntegerField(default=None)),
            ],
        ),
    ]
